### ISSUE TITLE
date time format

### ISSUE THREAD

**Issue by susilosarimun** [kristinemlarson/gnssrefl#1]
Could you please reformat date and time in the result from "yyyy doy UTCtime (decimal hours)" into "yyyy-mm-dd HH:MM"

Thank you very much

Susilo

**Comment by kristinemlarson** [comment]
I uploaded a new version that adds the months, days, hours, minutes information, though not in your exact format.  use -mmdd True when you run gnssir

**Comment by susilosarimun** [comment]
Thank you very much

**Comment by kristinemlarson** [comment]
This change has been implemented
