### ISSUE TITLE
docker image feature request

### ISSUE THREAD

**Issue by kristinemlarson** [kristinemlarson/gnssrefl#101]
from @fgnievinski 

the docker image is configured to mount /etc/gnssrefl/refl_code/Files at:
C:\Users\fgnievinski\Documents\Docker\refl_code\Files

the whole Documents folder is backed up by default in Google Drive, MS OneDrive, etc.

so if the user downloads a year of rinex, they might be inadvertently keeping that in backup.

not sure if it's too late, but a better location might be directly the user home:
C:\Users\fgnievinski\Docker\refl_code\Files

**Comment by timdittmann** [comment]
@fgnievinski 
Thanks for the feedback.
By all means, please modify the `docker run` command to meet your requirements:
Currently, the `${pwd}` in the run command mounts the path of the location that you issue the run command.  We assumed this was simplest for many use cases (feedback welcome!).
For your request, you could switch directories and issue the run command from that desired path(C:\Users\fgnievinski\Docker), or alternatively modify the run command to explicitly mount the volume path you prefer when run from any local directory: 

e.g.:
```
docker run -it -v C:\Users\fgnievinski\Docker\refl_code:/etc/gnssrefl/refl_code/ -v C:\Users\fgnievinski\Docker\refl_code\Files:/etc/gnssrefl/refl_code/Files --name gnssrefl ghcr.io/kristinemlarson/gnssrefl:latest /bin/bash 
```

Please let us know if we can assist further in clearing this up.
