### ISSUE TITLE
check that our code correctly reads/translates RINEX 4

### ISSUE THREAD

**Issue by kristinemlarson** [kristinemlarson/gnssrefl#161]
please find a station where the 30 sec datafile is in RINEX 4 and check that it still works on our docker
and the mac.  if you are looking for a station to try, check out the recent IGS mail on the topic.

**Comment by timdittmann** [comment]
Test 1:
Identified Rinex4 file (station LLAG00ESP after ~19 July 2023).
Successfully ran `rinex2snr LLAG00ESP 2023 212` on Mac and Docker.

Test 2:
Converted [single day .sbf file](https://data.unavco.org/archive/gnss/raw/2023/212/) from EarthScope to rinex4 using sbf2rin (septentrio rxtools executable).
`./sbf2rin -f p7092120.23_a.sbf -l  -R4 -s`
Then converted this file to SNR file using rinex2snr with -nolook flag.
`rinex2snr p70900USA 2023 212 -nolook true -samplerate 15` 
Then, for the same day/station, ran rinex2snr for rinex3 available in Earthscope archive.
`rinex2snr p70900USA 2023 213 -archive unavco -samplerate 15`

SNR output files are identical.
