### ISSUE TITLE
The "vwc" command is not working properly

### ISSUE THREAD

**Issue by Septyaz** [kristinemlarson/gnssrefl#197]
Screenshots If applicable, add screenshots to help explain your problem.

System (please complete the following information):

OS: Linux (Ubuntu)

**Describe the bug**
The "vwc" command for measuring soil moisture does not produce a .txt file, even though I have followed the command in the example case in the following link: https://gnssrefl.readthedocs.io/en/latest/pages/first_drivethru.html 

**To Reproduce**
I have tried all the sample cases provided on the following link https://gnssrefl.readthedocs.io/en/latest/pages/first_drivethru.html and followed the given commands. However, none of the sample cases produced a .txt file as described in the statement "These soil moisture estimates are written to a file; its location is written to the screen."

**Expected behavior**
According to the explanation provided on the link https://gnssrefl.readthedocs.io/en/latest/pages/first_drivethru.html in the case study of Boulder, Colorado, USA, after the "vwc" command such as "vwc mfle 2016 -year_end 2019," there should be a directory containing soil moisture estimate files in .txt format.

**Additional context**
If it's in accordance with the explanation, there should appear soil moisture estimate files in .txt format, as seen in the "Screenshot from 2023-10-01 22-29-46" image.

**Screenshots**
The result I obtained from the "vwc" command
![Screenshot from 2023-10-01 22-27-28](https://github.com/kristinemlarson/gnssrefl/assets/146207242/bcc26538-68e6-43d3-8272-bb1cfa938ade)
![Screenshot from 2023-10-01 22-27-35](https://github.com/kristinemlarson/gnssrefl/assets/146207242/419066f3-c343-43ed-8da0-84647addaa2f)
![Screenshot from 2023-10-01 22-27-43](https://github.com/kristinemlarson/gnssrefl/assets/146207242/2704a11c-a738-4678-9871-07601b8bf9c5)
![Screenshot from 2023-10-01 22-27-51](https://github.com/kristinemlarson/gnssrefl/assets/146207242/98c531ea-b7fd-4a6f-968b-c76b29f96e97)

The display after I ran the command.
![Screenshot from 2023-10-01 22-28-16](https://github.com/kristinemlarson/gnssrefl/assets/146207242/117af160-8b98-4682-b044-eacee86845ca)
![Screenshot from 2023-10-01 22-28-51](https://github.com/kristinemlarson/gnssrefl/assets/146207242/5832a2cd-5695-4172-bb0e-259e13423b08)

The command and explanation that I followed.
![Screenshot from 2023-10-01 22-29-04](https://github.com/kristinemlarson/gnssrefl/assets/146207242/92374685-58a3-4716-ba83-0f7d4065047b)
![Screenshot from 2023-10-01 22-29-20](https://github.com/kristinemlarson/gnssrefl/assets/146207242/69424acd-6838-4694-90de-ba1ec0634bd3)

An example of the soil moisture estimates file in .txt format that I expected.
![Screenshot from 2023-10-01 22-29-46](https://github.com/kristinemlarson/gnssrefl/assets/146207242/3d1d14f5-e81b-4900-acb1-701db9c63d88)

**Comment by kristinemlarson** [comment]
I habe an idea of why the file may not
Be created. I will try to test it today.

**Comment by kristinemlarson** [comment]
My idea about why this was not working for you does not appear to be correct. I thought perhaps the file directory was not being created, and thus the file itself should not be created either.  
But I deleted my files and tried again and the directory is being created.  for the station p475, these are the last 
three lines that are printed to the screen.  So when I look, the file is in $REFL_CODE/Files/p475/p475_vwc.txt

Saving to /Users/kristine/Documents/Research/Files/p475/p475_phase_vwc_result.png
Saving to /Users/kristine/Documents/Research/Files/p475/p475_vol_soil_moisture.png
>>> VWC results being written to  /Users/kristine/Documents/Research/Files/p475/p475_vwc.txt

Does this file get created for you?  In looking at the results for p475, I don't like that there is a big unexplained gap in 2020. There is a reason for that gap, so I will be making some edits.  But for the issue of where the results go, I wanted to check back that you are (or are not) getting this filename printed to the screen and that it is being created.

The output for vwc used to go to $REFL_CODE/Files, but it was getting messy with results for so many sites.
SO I started putting things in a subdirectory by default

Kristine

**Comment by kristinemlarson** [comment]
I would like to fix this for you - please let me know the current state of things when you have a chance.  As a separate manner, I have decided that p475 is not a very good example site.  So i have removed it from the example list for now. I still want to make sure the VWC code works - so if it is not creating output files in other test cases, I do want to know about that.
