### ISSUE TITLE
rinex2snr not recognizing local Rinex2.1 files

### ISSUE THREAD

**Issue by denivt** [kristinemlarson/gnssrefl#223]
Disclaimer! This is the first time I am making a bug report. Hopefully it will be readable, please send feedback on how the report has been written.

System (please complete the following information):

OS: Linux (Ubuntu 22.04.1 LTS)

Method you are running the code:
Docker 
**Describe the bug**
Not getting snr files after truing to run rinex2snr with local files

**To Reproduce**
1. commands run up to point of bug:
I start by downloading one own daily RINEX2.1 file, but the station is using all uppercase naming of the files, so i rename it:
docker run -it -v $(pwd)/refl_code:/etc/gnssrefl/refl_code/  --name gnssrefl ghcr.io/kristinemlarson/gnssrefl:latest /bin/bash
`mv GRAM0620.22O gram0620.22o `
Then i move the file to the /refl_code/ directory of my docker directory:
 `sudo mv /home/denivt/Downloads/gram0620.22o /home/denivt/GNSSIR/GNSSIR_Bulgaria/refl_code/`
2. Then after running:
 `rinex2snr gram 2022 62 -nolook T` I receive: 
3. Will first assume RINEX file  gram  year: 2022  doy: 62 is in the local directory
You Chose the No Look Option, but did not provide the needed RINEX file.
That took  0.06  seconds

4. Expected behavior: I expected an snr file to be created that i then would be able to work with. I don't know why after putting the file in the /refl_code/ directory i receive the discribed above error.

**Screenshots**
Here is a screenshot of how I runned the gnssrefl docker container for the first time (I ran it again for the first time just in case and updated it as the instructions recommended)
![image](https://github.com/kristinemlarson/gnssrefl/assets/127605009/3c63039b-53c7-4f20-9a66-6ebcff8b50f8)
Also here is the file in the folder:
![image](https://github.com/kristinemlarson/gnssrefl/assets/127605009/8216c324-e159-49bb-9492-2b8ef0c8e7e9)
These screenshots are for the second method i tried running rinex2snr:
The file in the correct folder:
![image](https://github.com/kristinemlarson/gnssrefl/assets/127605009/6b5b83be-07c2-4ee4-b704-5d2fa0716660)
![image](https://github.com/kristinemlarson/gnssrefl/assets/127605009/15356484-0430-4af1-ac8d-9ed89e77d5a2)

 
I tried also the option to put the files in the following folder:
refl_code/rinex/gram/2022/ and then I ran:
docker run -it -v $(pwd)/refl_code:/etc/gnssrefl/refl_code/ -v $(pwd)/refl_code/rinex/station/yyyy:/etc/gnssrefl/refl_code/rinex/gram/2022/ --name gnssrefl ghcr.io/kristinemlarson/gnssrefl:latest /bin/bash 
I dont know if i ran the command properly, but there are no clear instructions, but i tried 2 methods seen in the last screenshots, but still got the same results. 

**Additional context**
The files i try to use are in no other publically available archive, so there is no other way to run the code. They are part of a program, run together but the national hail suppression agency in Bulgaria and Sofia University.

**Comment by kristinemlarson** [comment]
Hi - thank you for posting this issue.  I happened to be logged on so I gave it a quick look.  I have posted comments and questions to Tim Dittmann as an issue, as he knows much more about dockers than I do.  And he also wrote the documentation.  I don't think the documentation  - as written - is correct, but I could be wrong. I believe the correct directory for the RINEX files should be in 2022/rinex/gram, not rinex/gram/2022.   That is how the code was meant to be used and that is how every other file is stored in gnssrefl (i.e. the snr files and the result files).  Given that it is the week before Thanksgiving, I am not sure Tim is working this next week, so I will do my best to help you in the mean time.

I use the term "local" directory all the time when I talk about files using the python install.  But in retrospect I don't think this is a useful concept - it is ambiguous and especially confusing when you are using the Docker (I am routinely confused by the DOcker).  So I did modify the code to print out exactly what the code thinks the local directory is. And it also says where else it is looking for the files.  I have just uploaded it to github, but it will take 15-20 minutes before a new Docker will be created.    

To get the new Docker, you'll need to do the "docker pull ghcr.io/kristinemlarson/gnssrefl:latest" command.

**Comment by kristinemlarson** [comment]
I started updating the docker install documentation. I am still working on it - but I think it has some useful stuff there. I Will have to look at it again on Monday.


https://github.com/kristinemlarson/gnssrefl/blob/master/docs/pages/docker_cl_instructions.md

**Comment by denivt** [comment]
Hello!

I had success, but planned to report it in more details, but the only way I
managed to make it work before your second email was with making the
directory you outlined in the updated documentation (the second one it
defaults to).
Thank you for the update to the code! It was really useful and I can make
it work for now!

**Comment by kristinemlarson** [comment]
Thank you so much for your original post. It was very helpful.
