### ISSUE TITLE
confused by the documentation for docker install

### ISSUE THREAD

**Issue by kristinemlarson** [kristinemlarson/gnssrefl#224]
Since I posted this -  I wrote my own advice for how to use the dockers.  But I did not remove your documentation because it makes more sense to have you look at it first.  

-------------------------------

 _If you have a lot of RINEX files and want to keep them organized, you should copy them into refl_code/rinex/station/yyyy/, where station is the lowercase 4char ID and yyyy is the year. You should then mount that directory in the docker run command as follows:_

Tim, I don't understand this documentation.  If the file is not in the local directory - the code expects the files to be in the directory called $REFL_CODE/yyyy/rinex/station.  

If you could update this documentation, that would be helpful. It would also be helpful to explain to people how to make sure their rinex file is in the local directory.

_The first time you run this container from a specific path, the Earthscope token will be installed once in the container at `` and locally at /localpath_of_dockerrun/refl_zones (the volume you mounted with the -v command)_

I also don't understand this one.  refl_zones?? I have included Kelly on this as well, as maybe there is something I am missing here.

_When running the software in the docker, plots/files will not print to the screen (think quickLook or daily_average utilities), but will be stored on the local machine in the directory that the docker run command was issued._

Best to say exactly which directory where they will show up.

This is from the jupyter install.
_If you have a lot of RINEX files and want to keep them organized, you should copy them into refl_code/rinex/station/yyyy/, where station is the lowercase 4char ID and yyyy is the year. You should then mount that directory in the docker run command as follows:_

So again, I have to ask if this is correct.  I know at one point Kelly was working on a "nolook" notebook so people would have an example, but I don't remember if that happened.  If it does exist, I think it would be helpful to point to it here.

**Comment by timdittmann** [comment]
- [ ] @timdittmann review docker instructions for mounting rinex file directory
- [ ] @timdittmann review docker instructions for where plots are saved locally
- [ ] @k-enloe and @timdittmann review instructions for jupyter install mounting directory of local rinex files

**Comment by kristinemlarson** [comment]
@timdittmann - i am not questioning whether you added the right verbiage on how to correctly mount a directory for rinex files. my issue is that when people run the code and used your instructions, they will find that the code does not look for files in the directory.  that is what alerted me to the issue - when someone tried to use your directions.  

the issue is similar for @k-enloe. and it may not be relevant for the notebooks as i don't know if we have a notebook to help people that want to use their own data.  if that is the case, then perhaps the best response is to remove that sentence about mounting that directory entirely.  the refl_zones is probably a typo - but i did not want to change it without your say so.

for both of you, if you want to give people instructions on how to mount a rinex directory, you have to also tell them how to get the code to find it.

**Comment by kristinemlarson** [comment]
I have done all I can do about this on my end, so I am closing this issue.  I will accept your PR when you make changes to the installs as we talked about.
