### ISSUE TITLE
file naming and rinex2snr conversion for GPS data on local machine

### ISSUE THREAD

**Issue by albinwwells** [kristinemlarson/gnssrefl#228]
**System**
I am running gnssrefl through Docker on my macOS system

**Issue**
Trouble converting RINEX observations to SNR with the rinex2snr function

**FIX**
The issue has been resolved via the following: I needed to rename the file (including the file extension). Initially, I had thought that I needed to somehow convert a .23O to .rnx file, but simply renaming it was sufficient. I also needed specify "samplerate=1" in the rinex2snr to align with the receiver sampling rate and subsequently the filename.

**Setup**
1. I have GPS data from [Cryologger](https://github.com/cryologger/glacier-velocity-tracker/tree/main) GPS system
2. Data was downloaded locally onto my machine (proprietary .ubx files)
3. U-blox files are converted to RINEX observation files (.23O) using Emlid Studio desktop application
4. RINEX observation files are renamed following gnssrefl naming convention requirements (e.g. 'AB0200USA_R_20231100000_01D_01S_MO.rnx')
5. Run rinex2snr: rinex2snr('AB0200USA', 2023, 110, snr=66, nolook=True, samplerate=1, orb='rapid')

**Expected behavior**
A SNR file to be generated. Instead, I received an error about a missing file

**Comment by kristinemlarson** [comment]
Thanks for posting!  This is very helpful and I am glad you got it to work.  The Rinex 2.11 and Rinex 3 naming conventions are super different - and by default rinex2snr expects Rinex 2.11 which has a very short and compact naming style.  in principle the code could check which kind of RINEX file it is (on the first line) and make decisions accordingly.
