### ISSUE TITLE
docker builds are failing because the hatanaka download or install is failing

### ISSUE THREAD

**Issue by kristinemlarson** [kristinemlarson/gnssrefl#234]
tim - please look into this-  or remove the dependency on the GSI website.

**Comment by kristinemlarson** [comment]
seems like an easy fix.  use the source we already have in gnssrefl.  

root@476f60f8cfb9:/tmp# wget https://terras.gsi.go.jp/ja/crx2rnx/RNXCMP_4.1.0_src.tar.gz
--2024-01-24 00:01:31--  https://terras.gsi.go.jp/ja/crx2rnx/RNXCMP_4.1.0_src.tar.gz
Resolving terras.gsi.go.jp (terras.gsi.go.jp)... 163.42.5.1
Connecting to terras.gsi.go.jp (terras.gsi.go.jp)|163.42.5.1|:443... connected.
ERROR: The certificate of ‘terras.gsi.go.jp’ is not trusted.
ERROR: The certificate of ‘terras.gsi.go.jp’ doesn't have a known issuer.

**Comment by timdittmann** [comment]
Hi @kristinemlarson I am traveling but will make this change over the weekend.

**Comment by kristinemlarson** [comment]
i uploaded the source you need to the proper source area.  it was living in docs, which does not help you.  
gnssrefl/crx2rnx.c
gnssrefl/rnx2crx.c

i think i did that right anyway.

**Comment by timdittmann** [comment]
Addressed in [this PR](https://github.com/kristinemlarson/gnssrefl/pull/235).

**Comment by kristinemlarson** [comment]
thank you tim
