### ISSUE TITLE
need to check the last spline in subdaily

### ISSUE THREAD

**Issue by kristinemlarson** [kristinemlarson/gnssrefl#263]
looks like it is extrapolating to end of day - and when you don't have observations - that is just wrong.

**Comment by fgnievinski** [comment]
it's easier to notice when ingesting only a few hours of the last day, then it'll complete the 24h -- extrapolating.

**Comment by kristinemlarson** [comment]
i noticed it when i was looking at the snow storm in boulder ...

**Comment by kristinemlarson** [comment]
I feel like it used to work - maybe i wrecked it by taking out the gaps.

**Comment by kristinemlarson** [comment]
i posted a change on this.  it only prints out spline values between your first and last observed RH.
