### ISSUE TITLE
Resolving 'You have been misled' error?

### ISSUE THREAD

**Issue by aaryan-rampal** [kristinemlarson/gnssrefl#270]
System (please complete the following information):

OS: [e.g. macOS, windows, etc...] Linux

Method you are running the code:
Locally via `pip install gnssrefl`

**Describe the bug**
I have a few local RINEX v2.11 files. I am trying to use `rinex2snr` to convert them into snr files and then run `gnssir` on them. When I run `rinex2snr` on them, I get this error: `You have been misled. There are no S1/S2 data in this file.` 

Using a quick grep search, I can see that this error originates from `gpssnr.f` when `npts == 0.` In the code right above this error message, there is this for loop:

```fortran
               s1 = obs(iobs(6),itrack)
               s2 = obs(iobs(7),itrack)
               ...
               ...
               ...
               if (s1.eq.0.d0 .and. s2.eq.0.d0) then
 c                 no data, SNR so do not print it
               else
                 call write_to_file(fileOUT, prn_pick, iprn,
      .           elev,azimuth, tod, s1,s2, s5)

                 npts = npts + 1
               endif
```

So, apparently, `s1` and `s2` are always zero in my RINEX file. I am not sure how `gpssnr.f` creates `obs` from the RINEX file. I am trying to debug this issue but have not gained progress because I am unfamiliar with fortran, and there seems to be no easy way to debug this because the fortran code is being used in the python program as a wrapper, and so I can't use a debugger for python or fortran exclusively. 

The RINEX files are my own local copy. I am assuming this is an error on my end with the formatting of the files not being in a way `rinex2snr` expects. This is the relevant line in the RINEX files. 
```
7    C1    P1    P2    L1    L2    S1    S2            # / TYPES OF OBSERV
```

**Comment by kristinemlarson** [comment]
If it was the case that all the SNR data were zeroes, maybe I should change the warning to "no non-zero SNR data?"
