### ISSUE TITLE
IOC tides download

### ISSUE THREAD

**Issue by jonauq2508** [kristinemlarson/gnssrefl#275]
I would like to know if is possible to analize the IOC tide data with the GNSSREFL package

**Comment by kristinemlarson** [comment]
the package allows you to download IOC tide data.  it doesn't do any analysis.  Use download_tides and the ioc network and the station name you need.  i think it also requires you input the starting and ending dates.  

https://gnssrefl.readthedocs.io/en/latest/api/gnssrefl.download_tides.html
