### ISSUE TITLE
No SNR file created

### ISSUE THREAD

**Issue by jonauq2508** [kristinemlarson/gnssrefl#299]
I am getting this error, while trying to analyze NMEA 0183 data 

![image](https://github.com/user-attachments/assets/dfd69588-44fe-4bbb-8570-28dc522bd26a)

**Comment by jonauq2508** [comment]
This is my NMEA 0183 file

**Comment by kristinemlarson** [comment]
i don't see a file on github.  in general you should not upload data files to github as they are too large.  and for the same reason, they cannot be emailed.  perhaps @MakanAKaregar can comment, as he wrote the nmea2snr module.
