### ISSUE TITLE
rinex2snr seems to search for RINEX files online even when using local RINEX files with the -nolook T command

### ISSUE THREAD

**Issue by Baizitang** [kristinemlarson/gnssrefl#314]
Hi,

I've encountered an issue while using the tool. When I use local RINEX files and the command, it still appears to search for RINEX files online. I am unsure if this is a bug in the program or just an incorrect output message.rinex2snr-nolook T

To provide more context, I will demonstrate two scenarios over two days:

In most cases, when it doesn't find the file I've locally named, it skips the search and runs normally.
However, in one case, it seems to find and search for RINEX files online, which should not happen with .-nolook T
Any insights on whether this behavior is intentional or an error would be helpful.

Thank you!!
1.code
![微信图片_20240911115720](https://github.com/user-attachments/assets/ffbf6b50-437f-4bd8-aeb8-440ac002b83e)
2.doy118
![微信图片_20240911115431](https://github.com/user-attachments/assets/3a68211d-5bcc-4567-af17-ed62c176d041)

3.doy119 （I have omitted some repetitive content in the middle.）
![微信图片_20240911115725](https://github.com/user-attachments/assets/943262ee-1f80-4c9f-a6eb-ee3c0dedf91b)
![微信图片_20240911115727](https://github.com/user-attachments/assets/7feea814-48c1-42bb-a43f-4b07f8965023)

**Comment by kristinemlarson** [comment]
please try the new version if you can.  it should no longer look for files when it already has one!

**Comment by Baizitang** [comment]
Thank you very much for your efforts, after I tried this issue I think this issue has been solved, but I have a new problem and don't know if I should continue to give feedback here.

I used the -gnss3 command to do this, but when downloading the track, the regular download part stopped, what is this error?

Should I download and upload the sp3 to the folder and solve it, and if so, how do I command to identify my local sp3?

1. code
![image](https://github.com/user-attachments/assets/426848a5-eb10-4691-ab83-ed3edfb01bd6)



1. The run was successful
![image](https://github.com/user-attachments/assets/176e24b6-212f-46bd-bee6-a985cd6fb351)

3. sp3 (GFZ FIN) download issue
![image](https://github.com/user-attachments/assets/f62b2ed5-6810-45d9-86d8-055c92d3f9c7)

**Comment by kristinemlarson** [comment]
I am away from my laptop and cannot
Help you with this now.

I would recommend using another orbit
Source.

Kristine M. Larson
***@***.***
https://www.kristinelarson.net <http://www.kristinelarson.net>
https://gnss-reflections.org
https://github.com/kristinemlarson

Have you tried reading the documentation?

**Comment by Baizitang** [comment]
Yes, I have read the documentation, as I used the same orbit for my previous data, and my goal is to process it with the same orbit. Thank you, I think I will try some other tracks instead.

**Comment by Baizitang** [comment]
Ok，thank you，I will try it.

**Comment by Baizitang** [comment]
OK，I get it！ Thanks.
