### ISSUE TITLE
Add SWE module and advanced soil moisture modules to gnssrefl

### ISSUE THREAD

**Issue by kristinemlarson** [kristinemlarson/gnssrefl#46]
Update April 4, 20223 : I am consolidating two issues here. Both are related to improvements to our environmental products. Originally this issue was only for SWE.  The link to soil moisture issue is below.  I am still willing to add an update for it, but am going to close it as a separate issue because it will not be done by our primary team.  It will have to come from the community.

https://github.com/kristinemlarson/gnssrefl/issues/50

gnssrefl is a python version of the code used in the PBO H2O project, https://gnss-reflections.org/maps.  one of the products of that project was snow depth.  We made a special effort to make a SWE product as well. We have that SWE code in matlab and it would make sense to port it to python to include it here. If someone from the cryo world would volunteer to do this port, I would happily provide the Matlab code. It is not terribly long or complicated code. It was written under the leadership of Eric Small, with an abandoned version in R written by James McCreight, and a Matlab version written by Mark Raleigh.

**Comment by derekpickell** [comment]
Hi Kristine! Would love to take a look... I've been porting a lot of cryo-related Matlab code into python recently and can give this a try.

**Comment by kristinemlarson** [comment]
I have found the code. It was originally written in R to analyze multiple years of hundreds of stations, and then ported to Matlab. I stripped it down so that it acts on a single station and a single year. Nevertheless, it is very clear to me that the only way this port to python will be successful is if the matlab code is first digested and improved (i.e. functions were not effectively used in the version I am giving you and the "main code" is far too long). If you are ready to digest the matlab to see what this python port would entail- I am happy to pass it on to you.

**Comment by derekpickell** [comment]
Sounds to me like it needs further modularization. Will have a better idea what I'm getting myself into once I lay eyes on the existing code... I've sent you an email.

**Comment by kristinemlarson** [comment]
I have placed the stripped-down code in a private github repository for now.  I have test cases so you can be sure you are getting the same answer in Matlab as in python. Anyone interested in trying to port it can contact me via email for access. Thanks, Kristine

**Comment by kristinemlarson** [comment]
i don't see much interest in this from the hydrology, atmospheric, and soil moisture communities, so am moving it for now.
