### ISSUE TITLE
Soil Moisture code for sites with significant vegetation

### ISSUE THREAD

**Issue by kristinemlarson** [kristinemlarson/gnssrefl#50]
Our current soil moisture module (vwc) is based on the operational PBO H2O model. This worked well in the grasslands and savannahs of the western U.S. These regions are generally categorized as semi-arid. We know this model fails for regions with vegetation water content of > 2kg/m/m. Clara Chew developed a better model for these more challenging sites.  It was coded in Matlab - and could easily be ported to python.  Let me know if you are interested in tackling this port. For details on Clara's work, you can look at  https://www.kristinelarson.net/wp-content/uploads/2015/10/ChewSmallLarson2015_withoutFront.pdf

**Comment by kristinemlarson** [comment]
I am consolidating this issue with the SWE issue.

**Comment by kristinemlarson** [comment]
ETH might have an interest?

**Comment by mnkosary** [comment]
Hello. I read Clara's work and I am so interested in this topic. I wanted to ask you, are the codes for this work available?

**Comment by kristinemlarson** [comment]
I don't have this code working.
