### ISSUE TITLE
readthedocs rendering 

### ISSUE THREAD

**Issue by timdittmann** [kristinemlarson/gnssrefl#88]
Read the docs is not rending bulleted lists from markdown pages.

for example: 
RTD: https://gnssrefl.readthedocs.io/en/latest/pages/new_station.html 
source markdown: https://github.com/kristinemlarson/gnssrefl/blob/master/docs/pages/new_station.md

**Comment by kristinemlarson** [comment]
It seems to work now.  Can we set this as closed?
