### ISSUE TITLE
why did not find the UNR database, I have station_pos.db file

### ISSUE THREAD

**Issue by 1026689430** [kristinemlarson/gnssrefl#89]

**Comment by timdittmann** [comment]
@1026689430: can you provide some context for this issue, particularly with respect to how you are using the gnssrefl software.  The type of information we are looking for is covered in the following template: https://github.com/kristinemlarson/gnssrefl/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by 1026689430** [comment]
I downloaded, but it didn't work

**Comment by timdittmann** [comment]
@1026689430 Thank you for the code:
Could you please add [additional context](https://github.com/kristinemlarson/gnssrefl/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) so we can narrow our assistance?  Specifically aspects like OS, dockers, etc.  Thanks!

**Comment by 1026689430** [comment]
it is solved , thank you professor
