### ISSUE TITLE
no link to utilities

### ISSUE THREAD

**Issue by kristinemlarson** [kristinemlarson/gnssrefl#93]
https://gnssrefl.readthedocs.io/en/latest/

There is no link to utilities.

**Comment by timdittmann** [comment]
Currently,
The main landing [page ](https://github.com/kristinemlarson/gnssrefl/blob/master/docs/index.rst)
Has a '[workflow](https://gnssrefl.readthedocs.io/en/latest/pages/func_and_utils_doc.html#workflow)' link to [func_and_utils](https://github.com/kristinemlarson/gnssrefl/blob/master/docs/pages/func_and_utils_doc.md)
which includes a [link](https://gnssrefl.readthedocs.io/en/latest/pages/utilities.html) to [utilities](https://github.com/kristinemlarson/gnssrefl/blob/master/docs/pages/utilities.md).

We can change this layout however you prefer and/or rename 'workflow'?
