### ISSUE TITLE
arcs crossing midnight

### ISSUE THREAD

**Issue by kristinemlarson** [kristinemlarson/gnssrefl#94]
the code currently throws out arcs that cross midnight. this is easy enough to fix by tacking on the data from
 the previous day (if it exists).  if someone wants to take a stab at this, i can easily set out the method for you.

**Comment by fgnievinski** [comment]
can you give some pointers, please?

**Comment by kristinemlarson** [comment]
I’ll give it a look see. Long time since i worked on it.

Kristine M. Larson
***@***.***
https://www.kristinelarson.net <http://www.kristinelarson.net>
https://gnss-reflections.org
https://github.com/kristinemlarson

Have you tried reading the documentation?
