### ISSUE TITLE
failed links to unavco resources

### ISSUE THREAD

**Issue by kristinemlarson** [kristinemlarson/gnssrefl#95]
Many of the use cases that showcase data archived at unavco now have dead links
to the unavco facility.  If there is a new scenario for these station pages, the links should be fixed.  If not,
they should be removed. Example: 
https://www.unavco.org/instrumentation/networks/status/nota/overview/P475

**Comment by timdittmann** [comment]
Those links were dead due to a temporary outage that has been repaired.
